name: deploy website
on: [pull_request]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: amondnet/now-deployment@v2.0.1
        with:
          zeit-token: ${{ secrets.ZEIT_TOKEN }}
          zeit-team-id: team_aGZBhyAMbRwDHX5s4pSZI5Ax
          now-args: '--prod'
          now-org-id: 'team_aGZBhyAMbRwDHX5s4pSZI5Ax'
          now-project-id: 'QmRq6QAxHd6oad2KsCaJtPJ4efjw29STVEFc7ZQiSTkmVQ'
