name: Linting

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1

      - name: Install Prettier
        run: yarn add prettier

      - name: Lint Prettier
        run: yarn lint:prettier
        env:
          CI: true
